// CPU benchmark table: built from the PassMark CPU list (single-thread "thread", multi-thread "cpumark", launch "date").
// The data is downloaded on the user's machine (`npm run cpu-data`) into data/cpu-benchmarks.json and never committed:
// PassMark data is for personal use. Nothing here contains benchmark numbers.
import { readFileSync, writeFileSync, existsSync, mkdirSync, statSync } from 'node:fs';
import { dirname } from 'node:path';
import { parseRobots, USER_AGENT } from './fetcher.js';
import { detectBlock } from './extract.js';

export const LOCAL_TABLE = 'data/cpu-benchmarks.json';
const SHIPPED_TABLE = new URL('./cpu-benchmarks.json', import.meta.url);
export const PASSMARK_PAGE = 'https://www.cpubenchmark.net/CPU_mega_page.html';
export const PASSMARK_DATA = 'https://www.cpubenchmark.net/data/';

/** Map a benchmark-site CPU name to the key used by specs.js/score.js (see cpuKey in score.js). */
export function normalizeCpuName(name) {
  const n = String(name).toLowerCase().replace(/@.*$/, ' ').replace(/\(r\)|\(tm\)|®|™/g, ' ').replace(/\s+/g, ' ').trim();
  let m;
  if ((m = n.match(/core\s*ultra\s*([579])\s*(\d{3})([a-z]{0,2})\b/))) return { key: `ultra ${m[1]} ${m[2]}${m[3]}` };
  if ((m = n.match(/\bcore\s*(i[3579])\s*-?\s*(\d{3,5})([a-z]{0,2}\d?)\b/))) return { key: `${m[1]}-${m[2]}${m[3]}` };
  if ((m = n.match(/\bryzen\s*([3579])\s*(pro\s*)?(\d{4})([a-z]{0,2})\b/))) return { key: `ryzen ${m[1]} ${m[3]}${m[4]}`, variant: m[2] ? 'pro' : null };
  if ((m = n.match(/\bapple\s*(m[1-4])(?:\s*(pro|max|ultra))?\b/))) return { key: `apple ${m[1]}${m[2] ? ' ' + m[2] : ''}` };
  if ((m = n.match(/\b(celeron|pentium(?: silver| gold)?|athlon(?: silver| gold)?)\s*([a-z]?\d{3,4}[a-z]?)\b/))) return { key: `${m[1]} ${m[2]}` };
  if ((m = n.match(/\bintel\s*(n\d{3})\b/))) return { key: m[1] };
  return null;
}

const MONTHS = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec'];
export function parseLaunch(v) {
  const m = String(v ?? '').trim().toLowerCase().match(/^([a-z]{3})\w*\s+(\d{4})$/) ;
  if (m && MONTHS.includes(m[1])) return `${m[2]}-${String(MONTHS.indexOf(m[1]) + 1).padStart(2, '0')}`;
  const q = String(v ?? '').match(/q([1-4])\s*'?\s*(\d{4})/i);
  if (q) return `${q[2]}-${String((+q[1] - 1) * 3 + 1).padStart(2, '0')}`;
  const y = String(v ?? '').match(/^(\d{4})$/);
  return y ? `${y[1]}-01` : null;
}
const toNum = v => {
  if (typeof v === 'number') return Number.isFinite(v) && v > 0 ? v : null;
  const s = String(v ?? '').replace(/[^0-9.]/g, '');
  return s ? Number(s) || null : null;
};

/**
 * Build the lookup table from PassMark-style rows ({name, cpumark, thread, date, cat}). Several names mapping to one key
 * (clock suffixes, core-count variants) are merged when their scores agree within 10%, otherwise marked ambiguous.
 */
export function buildBenchmarkTable(rows, { source = 'PassMark CPU Mark (cpubenchmark.net)', fetchedAt = new Date().toISOString() } = {}) {
  const groups = new Map();
  for (const r of rows) {
    const k = normalizeCpuName(r.name);
    if (!k) continue;
    const e = { name: String(r.name), multi: toNum(r.cpumark ?? r.multi), single: toNum(r.thread ?? r.single), released: parseLaunch(r.date ?? r.released), cat: r.cat ?? null, variant: k.variant ?? null };
    if (e.multi == null && e.single == null) continue;
    if (!groups.has(k.key)) groups.set(k.key, []);
    groups.get(k.key).push(e);
  }
  const cpus = {};
  for (const [key, list0] of groups) {
    const plain = list0.filter(e => !e.variant);
    const list = plain.length ? plain : list0; // prefer non-PRO entries; PRO only as a fallback
    const spread = f => { const v = list.map(e => e[f]).filter(x => x != null); return v.length ? [Math.min(...v), Math.max(...v)] : null; };
    const s = spread('single'), m = spread('multi');
    const ambiguous = [s, m].some(r => r && r[1] > r[0] * 1.1);
    const avg = f => { const v = list.map(e => e[f]).filter(x => x != null); return v.length ? Math.round(v.reduce((a, x) => a + x, 0) / v.length) : null; };
    const released = list.map(e => e.released).filter(Boolean).sort()[0] ?? null;
    cpus[key] = ambiguous
      ? { ambiguous: true, names: list.map(e => e.name), single: s, multi: m, released }
      : { name: list[0].name, single: avg('single'), multi: avg('multi'), released, laptop: list.some(e => /laptop|mobile/i.test(e.cat ?? '')) };
  }
  // Fixed scale per table: the 75th percentile of laptop CPUs maps to 50 points (independent of any OLX data).
  const pct = (f, p) => {
    let v = Object.values(cpus).filter(c => !c.ambiguous && c.laptop && c[f] != null).map(c => c[f]);
    if (v.length < 20) v = Object.values(cpus).filter(c => !c.ambiguous && c[f] != null).map(c => c[f]);
    v.sort((a, b) => a - b);
    return v.length ? v[Math.floor((v.length - 1) * p)] : null;
  };
  return {
    _about: 'Generated by `npm run cpu-data`. Personal-use copy of benchmark data; do not redistribute.',
    source, fetched_at: fetchedAt,
    units: { single: 'PassMark single-thread rating', multi: 'PassMark CPU Mark' },
    reference: { single: pct('single', 0.75), multi: pct('multi', 0.75), note: '75th percentile of laptop CPUs in this table = 50 points' },
    cpus,
  };
}

let cached = null, cachedStamp = null;
/** Local downloaded table if present, else the shipped (empty) one. Re-read when the file changes. */
export function loadBenchmarks({ path = LOCAL_TABLE } = {}) {
  const local = (path !== LOCAL_TABLE || !process.env.OLX_NO_LOCAL_DATA) && existsSync(path);
  const stamp = local ? `${path}:${statSync(path).mtimeMs}` : 'shipped';
  if (cached && stamp === cachedStamp) return cached;
  try { cached = JSON.parse(readFileSync(local ? path : SHIPPED_TABLE, 'utf8')); } catch { cached = { cpus: {}, reference: {}, units: {} }; }
  cachedStamp = stamp;
  return cached;
}

export function saveBenchmarks(table, path = LOCAL_TABLE) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(table, null, 1));
  cached = null;
  return { path, cpus: Object.keys(table.cpus).length, ambiguous: Object.values(table.cpus).filter(c => c.ambiguous).length };
}

/** Accept PassMark JSON ({data:[...]}, as served by /data/), a plain array, or CSV with name/cpumark/thread/date columns. */
export function parseBenchmarkFile(text) {
  const t = String(text).trim();
  if (t.startsWith('{') || t.startsWith('[')) {
    const j = JSON.parse(t);
    return Array.isArray(j) ? j : Array.isArray(j.data) ? j.data : [];
  }
  const lines = t.split(/\r?\n/).filter(Boolean);
  const split = l => l.match(/("([^"]|"")*"|[^,]*)(,|$)/g).slice(0, -1).map(c => c.replace(/,$/, '').replace(/^"|"$/g, '').replace(/""/g, '"'));
  const head = split(lines[0]).map(h => h.trim().toLowerCase());
  return lines.slice(1).map(l => Object.fromEntries(split(l).map((v, i) => [head[i], v])));
}

/**
 * Download the PassMark CPU list from the user's machine: robots.txt check, then the list page (for its session cookie)
 * and the JSON data it loads. Honest User-Agent, no retries; stops on block/captcha.
 */
export async function fetchPassmark({ http = defaultHttp, sleep = ms => new Promise(r => setTimeout(r, ms)), log = console.log } = {}) {
  const robots = await http('https://www.cpubenchmark.net/robots.txt', {});
  const allowed = robots.status === 200 ? parseRobots(robots.body) : () => true;
  if (robots.status !== 200 && robots.status !== 404) throw new Error(`robots.txt returned HTTP ${robots.status}; not downloading`);
  for (const u of [PASSMARK_PAGE, PASSMARK_DATA]) if (!allowed(u)) throw new Error(`robots.txt disallows ${u}; save the data manually and use --file`);
  log(`GET ${PASSMARK_PAGE}`);
  const page = await http(PASSMARK_PAGE, {});
  const b1 = detectBlock(page.status, page.body);
  if (b1 || page.status !== 200) throw new Error(`list page: ${b1 ?? 'HTTP ' + page.status}`);
  await sleep(3000);
  const url = `${PASSMARK_DATA}?_=${Date.now()}`;
  log(`GET ${url}`);
  const data = await http(url, { cookie: page.cookie, referer: PASSMARK_PAGE, xhr: true });
  const b2 = detectBlock(data.status, data.body);
  if (b2 || data.status !== 200) throw new Error(`data endpoint: ${b2 ?? 'HTTP ' + data.status}`);
  const rows = parseBenchmarkFile(data.body);
  if (!rows.length) throw new Error('data endpoint returned no CPU rows (format changed?)');
  return rows;
}

async function defaultHttp(url, { cookie, referer, xhr } = {}) {
  const headers = { 'User-Agent': USER_AGENT, 'Accept-Language': 'en' };
  if (cookie) headers.Cookie = cookie;
  if (referer) headers.Referer = referer;
  if (xhr) { headers['X-Requested-With'] = 'XMLHttpRequest'; headers.Accept = 'application/json, text/javascript, */*; q=0.01'; }
  const res = await fetch(url, { headers, signal: AbortSignal.timeout(60000) });
  const set = res.headers.getSetCookie?.() ?? [];
  return { status: res.status, body: await res.text(), cookie: set.map(c => c.split(';')[0]).join('; ') };
}
